version: 2.1

jobs:
  beta-android:
    machine:
      image: circleci/android:api-30-node
    steps:
      # Step 1: Checkout code
      - checkout

      # Step 2: Install necessary dependencies for Java setup
      - run:
          name: Install prerequisites
          command: |
            sudo apt-get update
            sudo apt-get install -y curl

      # Step 3: Set up Java JDK 17
      - run:
          name: Setup Java JDK 17
          command: |
            curl -sL "https://github.com/actions/setup-java/releases/download/v4.2.1/setup-java" -o setup-java.sh
            chmod +x setup-java.sh
            ./setup-java.sh -v adopt@17
            echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $BASH_ENV
            echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $BASH_ENV

      # Step 4: Prepare and run Android scripts
      - run:
          name: Prepare Android Environment
          command: bash scripts/prepare-android.sh

      - run:
          name: Run Beta Android Script
          command: bash scripts/beta-android.sh

workflows:
  beta:
    jobs:
      - beta-android
