version: 2.1

jobs:
  beta-android:
    docker:
      - image: cimg/android:2024.11.1-node
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Ruby Gems
          command: bundle install
      - run:
          name: Prepare Android
          command: bash scripts/prepare-android.sh
      - run:
          name: Run Beta Android Script
          command: bash scripts/beta-android.sh

workflows:
  beta:
    jobs:
      - beta-android
