# .circleci/config.yml
version: 2.1
jobs:
  beta-android:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - run:
          command: |
            bash scripts/prepare-android.sh
            bash scripts/beta-android.sh

workflows:
  beta:
    jobs:
      - beta-android