version: 2.1

jobs:
  beta-android:
    docker:
      - image: cimg/android:2024.11
    steps:
      - checkout
      - run:
          command: |
            bash scripts/prepare-android.sh
            bash scripts/beta-android.sh

workflows:
  beta:
    jobs:
      - beta-android
