version: 2.1

jobs:
  beta-android:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
      - run:
          name: Add Google Cloud SDK GPG key
          command: |
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      - run:
          name: Set JAVA_HOME to Java 17
          command: |
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
            echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $BASH_ENV
      - run:
          command: |
            bash scripts/prepare-android.sh
            bash scripts/beta-android.sh

workflows:
  beta:
    jobs:
      - beta-android
