# .circleci/config.yml
version: 2.1
jobs:
  beta-android:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout

      # Add the missing GPG key for cloud-sdk
      - run:
          name: Add GPG Key for cloud-sdk
          command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0BA5CE6DC6315A3

      # Update APT repositories
      - run:
          name: Update APT repositories
          command: sudo apt-get update

      # Install Java 17
      - run:
          name: Install Java 17
          command: |
            sudo apt-get install -y openjdk-17-jdk
            java -version

      # Set JAVA_HOME to Java 17
      - run:
          name: Set JAVA_HOME to Java 17
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
            source $BASH_ENV
            echo "JAVA_HOME is set to: $JAVA_HOME"

      # Ensure scripts are executable
      - run: chmod +x scripts/*.sh

      # Install Bundler
      - run: gem install bundler:2.6.2

      # Install dependencies from Gemfile
      - run: bundle install

      # Run prepare script
      - run: bash scripts/prepare-android.sh

      # Run beta-android script
      - run: bash scripts/beta-android.sh

workflows:
  build-test-adhoc:
    jobs:
      - beta-android

