version: 2.1

jobs:
  beta-android:
    docker:
      - image: jetbrains/qodana-jvm-android:latest
    steps:
      - checkout
      - run:
          name: Prepare Android
          command: bash scripts/prepare-android.sh
      - run:
          name: Run Beta Android Script
          command: bash scripts/beta-android.sh

workflows:
  beta:
    jobs:
      - beta-android
